# SPDX-FileCopyrightText: The Eigen Authors
# SPDX-License-Identifier: MPL-2.0

# Split-test parts that ei_add_test compiles as one executable per range
# "<first>-<last>" (see cmake/EigenTesting.cmake).  Each part repeats the
# frontend work of parsing and instantiating Eigen, so cheap parts compile
# faster together.
#
# Limits every range was checked against:
# - peak RSS of its compile about 4 GiB at most with g++-10, clang++-14 and
#   aarch64-linux-gnu-g++-10 at the CI's Release flags (aarch64 g++-10 is the
#   hungriest: five ranges reach 4.06-4.29 GiB there);
# - summed runtime of its parts <= 300 s on every configuration of the weekly
#   pipeline, half the CI's 600 s retry timeout;
# - no part named in EigenSmokeTestList.cmake, and no test with
#   EIGEN_TEST_PART_<N> markers (ei_add_test rejects both).
# Adding or renumbering subtests inside a range grows its compile: re-measure
# the range, or split it, before relying on it.

set(ei_test_part_groups_adjoint "2-19" "20-24")
set(ei_test_part_groups_array_cwise "1-4" "5-6" "10-12" "13-16" "17-26" "27-30" "31-34" "35-38" "40-41")
set(ei_test_part_groups_array_for_matrix "2-9")
set(ei_test_part_groups_array_replicate "2-8")
set(ei_test_part_groups_array_reverse "2-11")
set(ei_test_part_groups_autodiff "2-6")
set(ei_test_part_groups_autodiff_scalar "2-7")
set(ei_test_part_groups_basicstuff "1-4" "5-8")
set(ei_test_part_groups_bicgstab "1-2" "3-6")
set(ei_test_part_groups_blasutil "2-3" "4-6" "7-8")
set(ei_test_part_groups_block "1-4" "6-10")
set(ei_test_part_groups_block_sparse_matrix "3-8" "10-17" "18-19")
set(ei_test_part_groups_bunchkaufman "1-4" "6-7")
set(ei_test_part_groups_cholesky "7-9")
set(ei_test_part_groups_clz "1-4")
set(ei_test_part_groups_commainitializer "1-2")
set(ei_test_part_groups_complex_components "1-3")
set(ei_test_part_groups_complex_qz "1-3" "4-6" "7-8" "9-10")
set(ei_test_part_groups_concat "1-15")
set(ei_test_part_groups_condition_estimator "1-4" "5-6")
set(ei_test_part_groups_conjugate_gradient "1-2" "3-6")
set(ei_test_part_groups_conservative_resize "2-6")
set(ei_test_part_groups_corners "2-5")
set(ei_test_part_groups_determinant "2-10")
set(ei_test_part_groups_dgmres "2-4" "5-6")
set(ei_test_part_groups_diagonal "3-5")
set(ei_test_part_groups_diagonalmatrices "2-5" "6-9" "10-11")
set(ei_test_part_groups_diagonalview "1-2")
set(ei_test_part_groups_eigensolver_complex "2-5")
set(ei_test_part_groups_eigensolver_generalized_real "2-3" "4-5")
set(ei_test_part_groups_eigensolver_generic "3-5")
set(ei_test_part_groups_EulerAngles "2-5")
set(ei_test_part_groups_fastmath "1-4")
set(ei_test_part_groups_geo_alignedbox "3-14")
set(ei_test_part_groups_geo_homogeneous "2-3")
set(ei_test_part_groups_geo_hyperplane "2-5")
set(ei_test_part_groups_geo_misc "1-10")
set(ei_test_part_groups_geo_orthomethods "2-6")
set(ei_test_part_groups_geo_parametrizedline "2-4")
set(ei_test_part_groups_geo_quaternion "1-3")
set(ei_test_part_groups_geo_transformations "1-2" "3-4" "5-6" "8-9")
set(ei_test_part_groups_gmres "1-3")
set(ei_test_part_groups_hessenberg "2-5")
set(ei_test_part_groups_householder_fastmath "1-2")
set(ei_test_part_groups_idrs "1-2")
set(ei_test_part_groups_incomplete_cholesky "1-2" "3-4")
set(ei_test_part_groups_incomplete_LUT "1-5")
set(ei_test_part_groups_initializer_list_construction "1-6")
set(ei_test_part_groups_inplace_decomposition "2-3" "4-5" "6-7")
set(ei_test_part_groups_integer_types "2-9")
set(ei_test_part_groups_inverse "2-5" "6-8")
set(ei_test_part_groups_jacobi "2-8")
set(ei_test_part_groups_jacobisvd "53-54")
set(ei_test_part_groups_jacobisvd_blocked "1-4" "5-6")
set(ei_test_part_groups_linearstructure "2-12")
set(ei_test_part_groups_lscg "1-5")
set(ei_test_part_groups_lsmr "2-6" "7-11")
set(ei_test_part_groups_lu "1-2" "3-4" "6-8" "10-16")
set(ei_test_part_groups_mapped_matrix "2-13")
set(ei_test_part_groups_mapstaticmethods "2-8")
set(ei_test_part_groups_mapstride "2-6")
set(ei_test_part_groups_matrix_cwise "1-2" "4-5")
set(ei_test_part_groups_matrix_exponential "1-2" "3-4" "5-6" "7-8")
set(ei_test_part_groups_matrix_power "2-3")
set(ei_test_part_groups_matrix_square_root "2-3")
set(ei_test_part_groups_miscmatrices "2-3")
set(ei_test_part_groups_nesting_ops "2-4")
set(ei_test_part_groups_no_automatic_resizing "1-3")
set(ei_test_part_groups_nomalloc "2-3" "4-8" "9-10")
set(ei_test_part_groups_nullary "2-12")
set(ei_test_part_groups_packetmath "1-15")
set(ei_test_part_groups_packetmath_gather "1-2")
set(ei_test_part_groups_polynomialutils "2-9")
set(ei_test_part_groups_prec_inverse_4x4 "2-3")
set(ei_test_part_groups_product_evaluators "1-4")
set(ei_test_part_groups_product_large "1-2" "3-4" "5-6" "7-8" "10-11")
set(ei_test_part_groups_product_mmtr "1-6")
set(ei_test_part_groups_product_notemporary "1-2" "3-5")
set(ei_test_part_groups_product_selfadjoint "2-9")
set(ei_test_part_groups_product_small "1-2" "3-6" "8-10" "11-13" "21-23" "31-32" "33-41" "42-51" "52-55")
set(ei_test_part_groups_product_symm "2-7" "8-10")
set(ei_test_part_groups_product_syrk "2-7")
set(ei_test_part_groups_product_trmv "2-6")
set(ei_test_part_groups_product_trsolve "1-4" "6-12" "13-17")
set(ei_test_part_groups_qr "2-4" "5-9" "11-12")
set(ei_test_part_groups_qr_colpivoting "1-2" "8-11")
set(ei_test_part_groups_qr_fullpivoting "1-3" "5-8")
set(ei_test_part_groups_qr_rand_colpivoting "6-9")
set(ei_test_part_groups_rand "2-15")
set(ei_test_part_groups_random_matrix "1-4" "5-7" "8-9" "10-11" "12-14" "15-16")
set(ei_test_part_groups_real_qz "2-5")
set(ei_test_part_groups_realview "7-8" "9-12")
set(ei_test_part_groups_redux "2-13")
set(ei_test_part_groups_ref "2-10")
set(ei_test_part_groups_reshape "1-7")
set(ei_test_part_groups_rvalue_types "2-5")
set(ei_test_part_groups_scaled_permutation "1-5")
set(ei_test_part_groups_schur_complex "2-5" "8-9" "10-11")
set(ei_test_part_groups_selfadjoint "2-7")
set(ei_test_part_groups_simplicial_cholesky "23-32")
set(ei_test_part_groups_skew_symmetric_matrix3 "1-3")
set(ei_test_part_groups_sparse_basic "4-5")
set(ei_test_part_groups_sparse_block "2-6")
set(ei_test_part_groups_sparse_extra "1-3" "5-6")
set(ei_test_part_groups_sparse_ordering "1-4")
set(ei_test_part_groups_sparse_product "1-2" "5-6")
set(ei_test_part_groups_sparse_ref "2-4")
set(ei_test_part_groups_sparse_scatter "1-3")
set(ei_test_part_groups_sparse_threaded_product "3-4")
set(ei_test_part_groups_sparselu "4-6" "7-10")
set(ei_test_part_groups_sparseqr "1-7")
set(ei_test_part_groups_special_functions "2-5")
set(ei_test_part_groups_special_members "1-2")
set(ei_test_part_groups_special_packetmath "2-4")
set(ei_test_part_groups_stable_norm "2-4" "5-7" "8-11" "12-13")
set(ei_test_part_groups_stable_norm_fastmath "1-2")
set(ei_test_part_groups_stddeque "2-5")
set(ei_test_part_groups_stddeque_overload "2-5")
set(ei_test_part_groups_stdlist "2-5")
set(ei_test_part_groups_stdlist_overload "2-5")
set(ei_test_part_groups_stdvector "2-5")
set(ei_test_part_groups_stdvector_overload "2-5")
set(ei_test_part_groups_structured_bccb "1-2" "5-7")
set(ei_test_part_groups_structured_bindings "1-5")
set(ei_test_part_groups_structured_cauchy "1-2" "3-4")
set(ei_test_part_groups_structured_dplr "3-4")
set(ei_test_part_groups_structured_dpr1 "4-5")
set(ei_test_part_groups_structured_norm "1-5")
set(ei_test_part_groups_structured_vandermonde "1-3")
set(ei_test_part_groups_structured_vandermonde_int_index "1-2")
set(ei_test_part_groups_swap "2-4")
set(ei_test_part_groups_tensor_image_patch "1-12")
set(ei_test_part_groups_tensor_intdiv "1-7")
set(ei_test_part_groups_tensor_uint128 "1-7")
set(ei_test_part_groups_threads_runqueue "1-3")
set(ei_test_part_groups_triangular_in_place "1-6" "7-10")
set(ei_test_part_groups_tridiagonal_eigensolver "4-5")
set(ei_test_part_groups_trsm_packet_cancellation "1-2")
set(ei_test_part_groups_umeyama "1-2" "4-7")
set(ei_test_part_groups_upperbidiagonalization "1-3" "4-5" "6-7" "8-10" "11-13")
set(ei_test_part_groups_vectorwise_norm "1-9" "10-13")
set(ei_test_part_groups_vectorwiseop "2-4" "5-8" "9-12")
set(ei_test_part_groups_visitor "2-14")
